swyddfa/arlunio

docs/using/tutorials/basics-1.rst
docs/using/tutorials/index.rst
scripts/devenv-setup.sh

Added new tutorial basics-1.rst to introduce Stylo to beginners, and changed to devenv-setup.sh to work on macs.

New tutorial and change to setup file

---

.gitignore
CHANGES.rst
Pipfile
setup.cfg
stylo/color/colorspaces.py
stylo/shape/__init__.py
stylo/shape/basic.py
stylo/shape/curves.py
tests/shape/test_basic.py
tests/shape/test_curves.py

- Add a new `Line` shape
- Add a new shape `ImplicitXY` that can draw curves defined in terms of `x` and `y`
- Update `Circle` and `Ellipse` to be able to draw themselves as a curve

Updates to Shapes

---

CHANGES.rst
Pipfile
setup.py
stylo/time/__init__.py
stylo/time/clock.py
stylo/time/event.py
stylo/time/timeline.py
stylo/utils.py
tests/time/test_timeline.py
tox.ini

This is related to #41.
So far we have 
- A `MessageBus` object in `stylo.utils` that will be used to broadcast events between objects
- A `Clock` object in `stylo.time` that is responsible for keeping time
- A `Timeline` in `stylo.time` object that will be the main object that users interact with.
Currently this allows for the creation of an animation as follows
```python
timeline = Timeline(seconds=10) 
@timeline.main
def my_animation(f, t):   # f = frame number, t = realtime
...
image(width, height, filename=timeline.filename)
timeline.render(filename="my-animation/frame.png") 
```
This will then render out each frame of animation and save it as a file
```
my-animation/frame-000.png
my-animation/frame-001.png
my-animation/frame-002.png
...
my-animation/frame-249.png
```
Which on a …

Adding a notion of Time [WIP]

---

README.md
docs/index.rst
pyproject.toml

- Add Read the Docs badges in the relevant places
- Change URLs to point to Read the Docs
Closes #78

Complete switch to Read the Docs

---

docs/_references.rst
docs/extend/expressions.rst
requirements.txt
stylo/__init__.py
stylo/math/__init__.py
stylo/math/expr.py

- Update `requirements.txt` to hopefully fix builds on ReadTheDocs
- Add a `trace` decorator that can be used to easily construct a `StyExpr` representation of a function.

Tweaks to the Docs

---

docs/changes.rst
docs/conf.py
docs/contributing/index.rst
docs/extending/index.rst
docs/index.rst
docs/locale/cy/LC_MESSAGES/changes.po
docs/locale/cy/LC_MESSAGES/contributing.po
docs/locale/cy/LC_MESSAGES/extending.po
docs/locale/cy/LC_MESSAGES/index.po
docs/locale/cy/LC_MESSAGES/using.po
docs/using/index.rst
tox.ini

- Added placeholders for the main elements to the documentation
- Proof of concept Welsh translation

Adding basic structure to the documentation

---

setup.py
stylo/loaders.py
stylo/shapes.py
tests/test_loaders.py
tests/test_shapes.py

**Improvements to collections**
- Entry points are no longer resolved on initial load, only the items
that are explicitly referenced will be loaded
**Attr based shape refactor**
- Hopefully this will make things easier going forward as we can
start to leverage features such as serialisation, validation and
attribute based metadata

Properties

---

docs/conf.py
stylo/doc/__init__.py
stylo/lib/basic.py

- Also added a docstring for the ellipse shape

The `stylo.doc` module can now be used as an extension

---

.flake8
.gitignore
MANIFEST.in
README.md
arlunio/__main__.py
arlunio/_shapes.py
arlunio/cli/__init__.py
arlunio/cli/repl.py
arlunio/cli/tutorial.py
arlunio/doc/directives.py
arlunio/image.py
setup.py
snapcraft.yaml
tests/cli/test_cli.py

**Packaging**
- There is now a snapped version of arlunio (not terribly useful, but a good proof of concept)
- Still need to figure out to include it as part of CI
**CLI**
- As part of building and testing the snap I was reminded how pendantic `Click` is about unicode encodings under Python 3 and decided it wasn't worth the hassle.
- I've fallen back to using the builtin `argparse` so that means we have one less dependency! :tada: 
I have however tried to "wrap" the argparse api by auto generating the cli from method signatures and docstrings..... we'll see how long that lasts :thinking:

Initial attempts at building a snap package

---

arlunio/_shapes.py
arlunio/image.py

- `Canvas` objects, should now be immutable, with addition operators
returning new instances of a canvas object.
- Tweaked the CSS for an Image's `_repl_html_` function so that low res
images should be displayed correctly on chrome.

Small tweaks

---

blog/gallery.py
blog/public/css/main.css
blog/requirements.txt
blog/templates/gallery.html

- Images are now placed in a random order 
- On mouse over, the image's title, author and avatar appear to give more information
- Progress bars!

Improvements to the gallery index

---

blog/public/css/main.css
blog/templates/gallery.html

- Simpler implementation of #164 which fixes the issue where clicking the image would do nothing
- Hopefully this implementation also fixes the issues on mobile devices :crossed_fingers:

Make images clickable again

---

blog/public/css/main.css
blog/templates/base.html
blog/templates/image.html

- Made it so that the page doesn't scroll as such, more like the content is a "window" in the middle
- Made it so that mobile devices can't zoom in on the page - will have to see what that's like in practice

Tweaks to the gallery layout

---

.github/workflows/python-pr.yml
.github/workflows/python-release.yml
.gitignore
.vscode/settings.json
.vscode/tasks.json
blog/public/css/main.css
blog/templates/base.html

Use nord color scheme for the gallery

---

blog/gallery.py
blog/src/gallery/Checkerboard.ipynb
blog/src/gallery/Rolling Hills.ipynb
blog/src/gallery/Simple Clock.ipynb

**Gallery Build**
- Gallery images are now found by looking for definitions with a return type of `ar.Image`
- Better handling of broken notebooks
- Add a `--skip-failures` option so that the gallery can be at least partially built
**Images**
- Realign images to changes in the library

Realign gallery build and images

---

.pre-commit-config.yaml
blog/src/gallery/Checkerboard.ipynb
blog/src/gallery/Rolling Hills.ipynb
blog/src/gallery/Simple Clock.ipynb
scripts/clean-notebooks.sh
tests/data/Pythagoras.ipynb

- Add local `pre-commit` hook that will ensure any notebooks added to the gallery won't contain any output cells
- Fix `Checkerboard` notebook

Bring back cleaning of notebooks

---

.github/workflows/blog-release.yml
changes/177.doc.rst
docs/contributing/ci/blog-release.rst
docs/contributing/ci/index.rst

Document and add cron trigger to the blog build

---

.github/workflows/python-lint.yml
changes/210.misc.rst
docs/contributing/ci/python-linting.rst

Adjust the linting trigger to be paths that are explicitly listed

---

.github/workflows/python-release.yml
docs/contributing/ci/python-release.rst
scripts/should-release.sh

Have a nightly build, but only release if there are changes

---

blog/gallery.py
blog/public/css/image.css
blog/public/css/main.css
blog/src/gallery/Checkerboard.ipynb
blog/src/gallery/Rolling Hills.ipynb
blog/src/gallery/Simple Clock.ipynb
blog/templates/base.html
blog/templates/image.html

- Realign gallery build and images to the new module structure
- Remove fontawesome icons in favour of feather icons
- Tweak css layouts so things hopefully look and perform nicer

Realign gallery

---

arlunio/math.py
arlunio/shape.py
changes/187.stdlib.rst

Add triangle shape

---

arlunio/doc/notebook.py
tests/doc/test_notebook.py

Tweak the output of the generated notebook
